### ISSUE TITLE
Empty Rule Drawing Instructions

### ISSUE THREAD

**Issue by fostfox** [ArnMips/lua-cpp-s101-integration#18]
#### In OUTPUT.txt for `datasset_map.xml`

```
Feature : [43] BCNSPP
 
---------------------------------------
```
```
Feature : [68] BUISGL
 
---------------------------------------
```
```
Feature : [117] BUAARE
 
---------------------------------------
```
`...`

and so on. total 135

**Comment by fostfox** [comment]
### fe2spRef - not Initialized
```xml
<features>
  <ID>43</ID>
  <Class>160</Class>
  <Classalias>BCNSPP</Classalias>
<...>
   <fe2sp_ref>
     <ref_id>2198</ref_id>
     <ref_type>110</ref_type>
     <orientation>255</orientation>
     <scamin>-1</scamin>
     <scamax>0</scamax>
     <isolated_point>
       <lat>-32.5877</lat>
       <lon>60.9535</lon>
     </isolated_point>
   </fe2sp_ref>
</features>
```
![Screenshot_2](https://user-images.githubusercontent.com/20596258/57091172-37d3a680-6d11-11e9-9409-e365594a5e80.png)
![Screenshot_1](https://user-images.githubusercontent.com/20596258/57091174-3904d380-6d11-11e9-8df2-78acfcf93c6f.png)

**Comment by fostfox** [comment]
@alexzakharov1980 

Если у `Feature` отсутствует ссылка на `Spatial`, то нет возможности узнать ее `PrimitiveType` тип (точка, кривая, поверхность...). 
Без PrimitiveType типа невозможно получить правила рисования для объекта. 
#### Пример Feature без поля `fe2sp_ref`
```
<features>
  <ID>68</ID>
  <Class>25</Class>
  <Classalias>BUISGL</Classalias>
</features>
```

**Comment by alexzakharov1980** [comment]
Так если нет spatial, т.е. координат, то как (точнее, где) мы его рисовать собираемся? Его все равно придется пропустить.BUISGL это Building, Single. Бывает и площадным, и точечным.Я могу вывести (в понедельник) в файл информацию о геометрических типах feature, но не думаю, что это важно.2 мая 2019 г. 22:05 пользователь Bogdan Arzhevitin <notifications@github.com> написал:@alexzakharov1980

Если у Feature отсутствует ссылка на Spatial, то нет возможности узнать ее PrimitiveType тип (точка, кривая, поверхность...).

Без PrimitiveType типа невозможно получить правила рисования для объекта.

Пример Feature без поля fe2sp_ref

<features>

  <ID>68</ID>

  <Class>25</Class>

  <Classalias>BUISGL</Classalias>

</features>

**Comment by fostfox** [comment]
@sasha223311

Получается, нужно пропускать такие объекты и возвращать после парсинга dataset_map.xml набор featureIDs без id таких объектов
